version: "3.7"

services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: task_manager_api:1.0
    container_name: task_manager_api
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      PHP_MEMORY_LIMIT: 500M
    networks:
      - default

  nginx-server:
    image: nginx:alpine
    container_name: task_manager_nginx
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - default

  db:
    image: postgres:12
    container_name: task_manager_postgres
    environment:
      POSTGRES_USER: task_m
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: tm_database
    ports:
      - 6543:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    external:
      name: jpspe
